runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: jinja2
  version: "2.6"
- name: pytz
  version: "2017.3"

handlers:
- url: /bootstrap
  static_dir: bootstrap
  
- url: /.*
  script: main.app

